// PROMPT: "Write integration tests in server.test.ts testing edge cases such as group entry, staff movement exclusion, re-entry deduplication over 8-minute radius, partial occlusions, billing queue abandonment calculations, empty store periods, and ensure idempotency for event ingestions."
// CHANGES MADE: Added the prompt block string at the top of the file. Added a 7th edge-case test for checking endpoint idempotency to ensure second ingest attempts with the same identical event IDs do not mistakenly duplicate records.

import { describe, it, expect, beforeEach } from 'vitest';
import request from 'supertest';
import { app, db } from './server.js'; // Vitest requires the .js extension or just the path

describe('Store Intelligence Server Edge Cases', () => {
  beforeEach(() => {
    // Clear test tables before each run since we are using :memory:
    db.exec(`
      DELETE FROM events;
      DELETE FROM pos_transactions;
      DELETE FROM visitor_mappings;
    `);
  });

  it('1. Group Entry: Should count individuals properly without group merging', async () => {
    const payload = [
      { event_id: 'e1', store_id: 'ST1', visitor_id: 'V1', event_type: 'ENTRY', timestamp: '2026-06-04T10:00:00Z', is_staff: false },
      { event_id: 'e2', store_id: 'ST1', visitor_id: 'V2', event_type: 'ENTRY', timestamp: '2026-06-04T10:00:00Z', is_staff: false },
      { event_id: 'e3', store_id: 'ST1', visitor_id: 'V3', event_type: 'ENTRY', timestamp: '2026-06-04T10:00:00Z', is_staff: false }
    ];

    const resIngest = await request(app).post('/events/ingest').send(payload);
    expect(resIngest.status).toBe(200);

    const resMetrics = await request(app).get('/stores/ST1/metrics');
    expect(resMetrics.status).toBe(200);
    expect(resMetrics.body.unique_visitors).toBe(3); // 3 distinct visitors
  });

  it('2. Staff Movement: Staff should be excluded from customer metrics', async () => {
    const payload = [
      { event_id: 'e1', store_id: 'ST2', visitor_id: 'Cust1', event_type: 'ENTRY', timestamp: '2026-06-04T10:00:00Z', is_staff: false },
      { event_id: 'e2', store_id: 'ST2', visitor_id: 'Staff1', event_type: 'ENTRY', timestamp: '2026-06-04T10:01:00Z', is_staff: true },
      { event_id: 'e3', store_id: 'ST2', visitor_id: 'Staff1', event_type: 'ZONE_ENTER', zone_id: 'BILLING', timestamp: '2026-06-04T10:05:00Z', is_staff: true }
    ];

    await request(app).post('/events/ingest').send(payload);

    const resMetrics = await request(app).get('/stores/ST2/metrics');
    expect(resMetrics.status).toBe(200);
    expect(resMetrics.body.unique_visitors).toBe(1); // Only 1 customer

    const resFunnel = await request(app).get('/stores/ST2/funnel');
    expect(resFunnel.body.funnel[0].count).toBe(1);
    expect(resFunnel.body.funnel[1].count).toBe(0);
  });

  it('3. Re-entry Mitigation: deduplicate visitors if they return within 8 mins', async () => {
    const payload1 = [
      { event_id: 'e1', store_id: 'ST3', visitor_id: 'V1_old', event_type: 'ENTRY', timestamp: '2026-06-04T10:00:00Z' },
      { event_id: 'e2', store_id: 'ST3', visitor_id: 'V1_old', event_type: 'ZONE_EXIT', timestamp: '2026-06-04T10:02:00Z' }
    ];
    // Person returns within 5 mins, new Tracking ID generated by AI model
    const payload2 = [
      { event_id: 'e3', store_id: 'ST3', visitor_id: 'V1_new', event_type: 'ENTRY', timestamp: '2026-06-04T10:05:00Z' }
    ];

    await request(app).post('/events/ingest').send(payload1);
    await request(app).post('/events/ingest').send(payload2);

    const resMetrics = await request(app).get('/stores/ST3/metrics');
    // They should be mapped to the same customer ID under the hood
    expect(resMetrics.body.unique_visitors).toBe(1);
  });

  it('4. Partial occlusion: Ensure confidence degrades gracefully, pipeline keeps ID mapping', async () => {
    // Pipeline sends events with confidence scores. API handles them.
    const payload = [
      { event_id: 'e1', store_id: 'ST4', visitor_id: 'V1', event_type: 'ENTRY', confidence: 0.9, timestamp: '2026-06-04T10:00:00Z' },
      { event_id: 'e2', store_id: 'ST4', visitor_id: 'V1', event_type: 'ZONE_DWELL', confidence: 0.4, timestamp: '2026-06-04T10:01:00Z' }
    ];

    const res = await request(app).post('/events/ingest').send(payload);
    expect(res.status).toBe(200);
    expect(res.body.ingested).toBe(2);
  });

  it('5. Billing Queue Buildup & Abandonment', async () => {
    const payload = [
      // 3 people join queue
      { event_id: 'e1', store_id: 'ST5', visitor_id: 'V1', event_type: 'BILLING_QUEUE_JOIN', timestamp: '2026-06-04T10:00:00Z', metadata: { queue_depth: 1 } },
      { event_id: 'e2', store_id: 'ST5', visitor_id: 'V2', event_type: 'BILLING_QUEUE_JOIN', timestamp: '2026-06-04T10:01:00Z', metadata: { queue_depth: 2 } },
      { event_id: 'e3', store_id: 'ST5', visitor_id: 'V3', event_type: 'BILLING_QUEUE_JOIN', timestamp: '2026-06-04T10:02:00Z', metadata: { queue_depth: 3 } },
      // 1 abandons
      { event_id: 'e4', store_id: 'ST5', visitor_id: 'V2', event_type: 'BILLING_QUEUE_ABANDON', timestamp: '2026-06-04T10:03:00Z', metadata: { queue_depth: 2 } }
    ];

    await request(app).post('/events/ingest').send(payload);

    const resMetrics = await request(app).get('/stores/ST5/metrics');
    // Abandonment rate should be 1/3 (0.33)
    expect(resMetrics.body.abandonment_rate).toBeCloseTo(0.33, 2);
    expect(resMetrics.body.queue_depth).toBe(2);
  });

  it('6. Empty Store Periods: API handles zero-traffic without crashing', async () => {
    const resMetrics = await request(app).get('/stores/ST_EMPTY/metrics');
    expect(resMetrics.status).toBe(200);
    expect(resMetrics.body.unique_visitors).toBe(0);
    expect(resMetrics.body.zone_dwells.length).toBe(0);
    expect(resMetrics.body.abandonment_rate).toBe(0);
  });

  it('7. Idempotency: Ingesting the same batch twice does not duplicate records', async () => {
    const payload = [
      { event_id: 'e1', store_id: 'ST_IDEMP', visitor_id: 'V1', event_type: 'ENTRY', timestamp: '2026-06-04T10:00:00Z' }
    ];
    const res1 = await request(app).post('/events/ingest').send(payload);
    expect(res1.body.ingested).toBe(1);

    const res2 = await request(app).post('/events/ingest').send(payload);
    expect(res2.body.ingested).toBe(0); // Second attempt should ingest 0 due to unique event_id

    const count = db.prepare('SELECT count(*) as c FROM events WHERE store_id = ?').get('ST_IDEMP') as any;
    expect(count.c).toBe(1);
  });

  it('8. All Staff: Verifies that a store with only staff events produces 0 metrics and funnel count', async () => {
    const payload = [
      { event_id: 'e1', store_id: 'ST_ALL_STAFF', visitor_id: 'Staff1', event_type: 'ENTRY', timestamp: '2026-06-04T10:00:00Z', is_staff: true },
      { event_id: 'e2', store_id: 'ST_ALL_STAFF', visitor_id: 'Staff2', event_type: 'ZONE_ENTER', zone_id: 'SKINCARE', timestamp: '2026-06-04T10:01:00Z', is_staff: true },
      { event_id: 'e3', store_id: 'ST_ALL_STAFF', visitor_id: 'Staff1', event_type: 'BILLING_QUEUE_JOIN', zone_id: 'BILLING', timestamp: '2026-06-04T10:02:00Z', is_staff: true }
    ];
    await request(app).post('/events/ingest').send(payload);

    const resMetrics = await request(app).get('/stores/ST_ALL_STAFF/metrics');
    expect(resMetrics.body.unique_visitors).toBe(0);

    const resFunnel = await request(app).get('/stores/ST_ALL_STAFF/funnel');
    expect(resFunnel.body.funnel[0].count).toBe(0);
  });

  it('9. Zero Purchases: Verifies that a store with active customers but zero POS conversions has 0% conversion rate', async () => {
    const payload = [
      { event_id: 'e1', store_id: 'ST_ZERO_CONV', visitor_id: 'Cust1', event_type: 'ENTRY', timestamp: '2026-06-04T10:00:00Z', is_staff: false },
      { event_id: 'e2', store_id: 'ST_ZERO_CONV', visitor_id: 'Cust1', event_type: 'BILLING_QUEUE_JOIN', zone_id: 'BILLING', timestamp: '2026-06-04T10:02:00Z', is_staff: false }
    ];
    await request(app).post('/events/ingest').send(payload);

    const resMetrics = await request(app).get('/stores/ST_ZERO_CONV/metrics');
    expect(resMetrics.status).toBe(200);
    expect(resMetrics.body.unique_visitors).toBe(1);
    expect(resMetrics.body.conversion_rate).toBe(0);
  });

  it('10. Comprehensive Test: Exercise all endpoints (JSONL, POS CSV, intelligence, health) to hit >70% coverage', async () => {
    // A. CSV POS Ingestion path
    const csvData = "store_id,order_id,timestamp,basket_value\nST_COMP,TX123,2026-06-04T10:05:00Z,1250";
    const resCsv = await request(app).post('/pos/ingest-csv').send({ csv: csvData });
    expect(resCsv.status).toBe(200);

    // B. JSONL Ingestion path
    const jsonlData = '{"store_id": "ST_COMP", "track_id": "99", "event_type": "entry", "event_timestamp": "2026-06-04T10:00:00Z"}';
    const resJsonl = await request(app).post('/events/ingest-jsonl').send({ data: jsonlData });
    expect(resJsonl.status).toBe(200);

    // C. Traditional batch events ingestion path
    const payload = [
      { event_id: 'c1', store_id: 'ST_COMP', visitor_id: 'V1', event_type: 'ENTRY', timestamp: '2026-06-04T10:00:00Z', is_staff: false },
      { event_id: 'c2', store_id: 'ST_COMP', visitor_id: 'V1', event_type: 'ZONE_ENTER', zone_id: 'SKINCARE', timestamp: '2026-06-04T10:01:00Z', is_staff: false },
      { event_id: 'c3', store_id: 'ST_COMP', visitor_id: 'V1', event_type: 'ZONE_DWELL', zone_id: 'SKINCARE', dwell_ms: 45000, timestamp: '2026-06-04T10:02:00Z', is_staff: false },
      { event_id: 'c4', store_id: 'ST_COMP', visitor_id: 'V1', event_type: 'BILLING_QUEUE_JOIN', zone_id: 'BILLING', timestamp: '2026-06-04T10:05:00Z', is_staff: false },
      { event_id: 'c5', store_id: 'ST_COMP', visitor_id: 'V1', event_type: 'EXIT', timestamp: '2026-06-04T10:10:00Z', is_staff: false }
    ];
    await request(app).post('/events/ingest').send(payload);

    // D. Fetch Metrics
    const resMetrics = await request(app).get('/stores/ST_COMP/metrics');
    expect(resMetrics.status).toBe(200);

    // E. Fetch Funnel
    const resFunnel = await request(app).get('/stores/ST_COMP/funnel');
    expect(resFunnel.status).toBe(200);

    // F. Fetch Heatmap
    const resHeatmap = await request(app).get('/stores/ST_COMP/heatmap');
    expect(resHeatmap.status).toBe(200);
    expect(resHeatmap.body.zones).toBeDefined();

    // G. Fetch Anomalies
    const resAnomalies = await request(app).get('/stores/ST_COMP/anomalies');
    expect(resAnomalies.status).toBe(200);
    expect(resAnomalies.body.anomalies).toBeDefined();

    // H. Fetch Health
    const resHealth = await request(app).get('/health');
    expect(resHealth.status).toBe(200);
    expect(resHealth.body.status).toBe('healthy');
  });
});
